"""Phase H release-candidate synthetic E2E coverage.

This test intentionally uses generated bytes and a fake video backend.  It proves the
full local lifecycle without depending on ffmpeg binaries, HEIC codecs, network, or
user media.
"""

from __future__ import annotations

import hashlib
import sqlite3
import struct
import time
from contextlib import closing
from ctypes import POINTER, Structure, byref, c_int, c_size_t, c_ulong, c_void_p
from pathlib import Path

from PIL import Image, ImageDraw

from smart_photo_triage.ai import AnalysisOptions, FakeVisionProvider, analyze_workspace
from smart_photo_triage.executor import apply_plan, doctor_workspace, rollback_transaction
from smart_photo_triage.grouping import BurstCandidate, group_burst_candidates, group_workspace
from smart_photo_triage.planner import (
    PlannerOptions,
    approve_plan,
    build_plan,
    preflight_plan,
)
from smart_photo_triage.preprocess import PreviewError, preprocess_workspace
from smart_photo_triage.review import ReviewStore
from smart_photo_triage.scanner import scan_library
from smart_photo_triage.workspace import initialize_workspace


class _ProcessMemoryCounters(Structure):
    _fields_ = [
        ("cb", c_ulong),
        ("page_fault_count", c_ulong),
        ("peak_working_set_size", c_size_t),
        ("working_set_size", c_size_t),
        ("quota_peak_paged_pool_usage", c_size_t),
        ("quota_paged_pool_usage", c_size_t),
        ("quota_peak_non_paged_pool_usage", c_size_t),
        ("quota_non_paged_pool_usage", c_size_t),
        ("pagefile_usage", c_size_t),
        ("peak_pagefile_usage", c_size_t),
        ("private_usage", c_size_t),
    ]


def _peak_rss_bytes() -> int | None:
    """Return the truthful process peak working set on Windows, when available."""
    try:
        from ctypes import sizeof, windll

        counters = _ProcessMemoryCounters()
        counters.cb = sizeof(counters)
        current_process = windll.kernel32.GetCurrentProcess
        current_process.restype = c_void_p
        get_memory_info = windll.psapi.GetProcessMemoryInfo
        get_memory_info.argtypes = [c_void_p, POINTER(_ProcessMemoryCounters), c_ulong]
        get_memory_info.restype = c_int
        if not get_memory_info(current_process(), byref(counters), sizeof(counters)):
            return None
        return int(counters.peak_working_set_size)
    except (ImportError, AttributeError, OSError):
        return None


class _SyntheticVideoBackend:
    """Deterministic contact-sheet backend for generated video fixture bytes."""

    def __init__(self) -> None:
        self.timestamps: dict[str, list[float]] = {}

    def probe_duration(self, path: Path) -> float:
        if path.name == "corrupt.mp4":
            raise PreviewError("synthetic corrupt video")
        return 12.0

    def read_frame(self, path: Path, timestamp: float) -> Image.Image:
        self.timestamps.setdefault(path.name, []).append(timestamp)
        return Image.new("RGB", (32, 20), (int(timestamp * 20) % 255, 80, 140))


def _snapshot(root: Path) -> dict[str, bytes]:
    if not root.exists():
        return {}
    return {
        path.relative_to(root).as_posix(): path.read_bytes()
        for path in sorted(root.rglob("*"))
        if path.is_file()
    }


def _make_quicktime(path: Path) -> None:
    # Small parseable QuickTime container.  Frames are supplied by the fake backend.
    mvhd_payload = b"\x00\x00\x00\x00" + struct.pack(">I", 2_085_000_000) + b"\x00" * 12
    mvhd = struct.pack(">I4s", len(mvhd_payload) + 8, b"mvhd") + mvhd_payload
    moov = struct.pack(">I4s", len(mvhd) + 8, b"moov") + mvhd
    ftyp_payload = b"qt  \x00\x00\x00\x00qt  "
    ftyp = struct.pack(">I4s", len(ftyp_payload) + 8, b"ftyp") + ftyp_payload
    path.write_bytes(ftyp + moov)


def _make_image(path: Path, index: int, *, duplicate_of: Path | None = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if duplicate_of is not None:
        path.write_bytes(duplicate_of.read_bytes())
        return
    image = Image.new("RGB", (48, 32), ((index * 31) % 255, 70, 130))
    draw = ImageDraw.Draw(image)
    draw.rectangle((index % 12, 4, 28, 20), fill=(220, 180, (index * 17) % 255))
    image.save(path, format="PNG")


def _bundle_rows(workspace) -> list[tuple[str, str, str]]:
    with closing(sqlite3.connect(workspace.database_path)) as connection:
        return connection.execute(
            """
            SELECT bm.bundle_id, bm.role, m.extension
            FROM bundle_member AS bm JOIN media_item AS m ON m.id=bm.media_id
            ORDER BY bm.bundle_id, bm.role
            """
        ).fetchall()


def test_phase_h_synthetic_e2e_isolated_idempotent_and_reversible(tmp_path: Path) -> None:
    source = tmp_path / "synthetic-source"
    source.mkdir()

    # H1 fixture ledger: 20+ images, exact duplicate, same-size unequal bytes, a >=4 burst,
    # false-chain control, HEIC/MOV/AAE bundle, two videos, corrupt image/video, missing EXIF,
    # and a Windows-reserved-name input. All files are synthetic.
    burst: list[Path] = []
    for index in range(4):
        path = source / f"20240506_07080{index}_burst.png"
        _make_image(path, index)
        burst.append(path)
    duplicate = source / "20240506_070900_duplicate.png"
    _make_image(duplicate, 20)
    _make_image(source / "20240506_070901_duplicate-copy.png", 20, duplicate_of=duplicate)
    for index in range(14):
        _make_image(source / f"202406{index + 1:02d}_010203_item.png", index + 30)
    # A same-size, different-content pair and a missing-EXIF item are both generated above.
    (source / "20240506_071000_CON_report.png").write_bytes(b"same-size-different-content-a")
    (source / "20240506_071001_CON_report-copy.png").write_bytes(b"same-size-different-content-b")
    (source / "20240506_071002_false-chain-A.png").write_bytes(b"false-chain-anchor")
    (source / "20240506_071003_false-chain-B.png").write_bytes(b"false-chain-middle")
    (source / "20240506_071004_false-chain-C.png").write_bytes(b"false-chain-tail--")
    (source / "corrupt.png").write_bytes(b"not an image")

    (source / "IMG_0001.HEIC").write_bytes(b"synthetic heic bundle member")
    _make_quicktime(source / "IMG_0001.MOV")
    (source / "IMG_0001.AAE").write_text("synthetic sidecar", encoding="utf-8")
    (source / "good.mp4").write_bytes(b"synthetic good video")
    (source / "corrupt.mp4").write_bytes(b"synthetic corrupt video")
    before = _snapshot(source)
    assert {
        "20240506_071000_CON_report.png",
        "20240506_071002_false-chain-A.png",
        "20240506_071003_false-chain-B.png",
        "20240506_071004_false-chain-C.png",
        "IMG_0001.HEIC",
        "IMG_0001.MOV",
        "IMG_0001.AAE",
        "good.mp4",
        "corrupt.mp4",
        "corrupt.png",
    } <= before.keys()
    false_chain = group_burst_candidates(
        [
            BurstCandidate(1, "2024-05-06T07:10:02", "0000000000000000", 0.5, "a"),
            BurstCandidate(2, "2024-05-06T07:10:03", "0000000000000001", 0.5, "b"),
            BurstCandidate(3, "2024-05-06T07:10:04", "0000000000000003", 0.5, "c"),
        ],
        distance_threshold=1,
    )
    assert false_chain.clusters[0].member_ids == (1, 2)

    workspace = initialize_workspace(tmp_path / "workspace")
    scanned = scan_library(workspace, source, hash_content=True)
    preprocessed = preprocess_workspace(workspace, video_backend=_SyntheticVideoBackend())
    groups = group_workspace(workspace)
    provider = FakeVisionProvider(model="phase-h-release", record_requests=True)
    analyzed = analyze_workspace(
        workspace,
        provider=provider,
        options=AnalysisOptions(batch_size=4),
    )

    # Inject one HUMAN decision and prove the bundle remains linked in the plan.
    review = ReviewStore(workspace)
    first_item = review.list_items(page_size=1).items[0]
    review.update_decision(
        int(first_item["id"]),
        category="01_家庭生活",
        disposition="KEEP",
        expected_revision=0,
    )
    output = tmp_path / "organized"
    first_plan = build_plan(workspace, PlannerOptions(output_root=output))
    second_plan = build_plan(workspace, PlannerOptions(output_root=output))
    assert first_plan.canonical_json() == second_plan.canonical_json()
    assert first_plan.plan_id == second_plan.plan_id
    assert preflight_plan(workspace, first_plan.plan_id).ok is False
    approve_plan(workspace, first_plan.plan_id)
    report = preflight_plan(workspace, first_plan.plan_id)
    assert report.ok

    bundle_entries = [
        entry
        for entry in first_plan.entries
        if entry.bundle_id and Path(entry.target_path).suffix.lower() in {".heic", ".mov", ".aae"}
    ]
    assert {Path(entry.target_path).suffix.lower() for entry in bundle_entries} >= {
        ".heic",
        ".mov",
        ".aae",
    }
    assert len({Path(entry.target_path).parent for entry in bundle_entries}) == 1
    assert len({Path(entry.target_path).stem.casefold() for entry in bundle_entries}) == 1
    assert any(entry.decision_source == "HUMAN" for entry in first_plan.entries)

    dry_run = apply_plan(workspace, report, dry_run=True)
    assert dry_run.state == "DRY_RUN"
    assert _snapshot(source) == before
    assert not _snapshot(output)

    applied = apply_plan(workspace, report, dry_run=False)
    assert applied.state == "DONE"
    output_after_first_apply = _snapshot(output)
    applied_again = apply_plan(workspace, report, dry_run=False)
    assert applied_again.state == "DONE"
    assert applied_again.transaction_id == applied.transaction_id
    assert _snapshot(output) == output_after_first_apply
    for entry in first_plan.entries:
        target = Path(entry.target_path)
        assert target.exists()
        assert hashlib.sha256(target.read_bytes()).hexdigest() == entry.expected_sha256
    diagnosis = doctor_workspace(workspace)
    assert diagnosis.ok
    rolled_back = rollback_transaction(workspace, applied.transaction_id)
    assert rolled_back.state == "ROLLED_BACK"
    assert _snapshot(source) == before
    assert not _snapshot(output)

    # The complete second pass has identical planning, no extra targets, and cache-only AI.
    second_scan = scan_library(workspace, source, hash_content=True)
    second_preprocess = preprocess_workspace(workspace, video_backend=_SyntheticVideoBackend())
    second_groups = group_workspace(workspace)
    second_analysis = analyze_workspace(
        workspace,
        provider=provider,
        options=AnalysisOptions(batch_size=4),
    )
    third_plan = build_plan(workspace, PlannerOptions(output_root=output))

    assert scanned.indexed_count >= 29
    assert second_scan.indexed_count == scanned.indexed_count
    assert second_scan.unchanged_count == scanned.indexed_count
    assert groups.duplicate_group_count >= 1
    assert groups.burst_group_count >= 1
    assert second_groups == groups
    assert analyzed.analyzed_count >= 18
    assert preprocessed.failed_count >= 2  # invalid HEIC plus corrupt video, isolated
    assert second_preprocess.cache_hit_count >= preprocessed.processed_count
    assert second_analysis.request_count == 0
    assert second_analysis.cache_hit_count >= analyzed.analyzed_count
    assert len(provider.requests) == analyzed.request_count
    assert third_plan.canonical_json() == first_plan.canonical_json()
    assert third_plan.plan_id == first_plan.plan_id
    assert not _snapshot(output)
    assert any(extension == ".mov" for _, _, extension in _bundle_rows(workspace))


def test_phase_h_1k_synthetic_full_lifecycle_benchmark_is_bounded(tmp_path: Path) -> None:
    """H4 records environment-specific metrics without a cross-machine timing gate."""
    source = tmp_path / "one-thousand-source"
    source.mkdir()
    seed = source / "IMG_20250101_000000_0000.png"
    _make_image(seed, 1)
    for index in range(1, 1000):
        _make_image(source / f"IMG_20250101_0000{index:04d}.png", index, duplicate_of=seed)
    before = _snapshot(source)
    workspace = initialize_workspace(tmp_path / "one-thousand-workspace")
    output = tmp_path / "one-thousand-output"

    started = time.perf_counter()
    scan = scan_library(workspace, source, hash_content=True)
    scan_elapsed = time.perf_counter() - started
    preview_started = time.perf_counter()
    first_preview = preprocess_workspace(workspace)
    preview_elapsed = time.perf_counter() - preview_started
    grouped = group_workspace(workspace)
    provider = FakeVisionProvider(model="phase-h-1k", record_requests=True)
    first_analysis = analyze_workspace(
        workspace, provider=provider, options=AnalysisOptions(batch_size=100)
    )
    plan = build_plan(workspace, PlannerOptions(output_root=output))
    approve_plan(workspace, plan.plan_id)
    report = preflight_plan(workspace, plan.plan_id)
    assert report.ok
    dry_run = apply_plan(workspace, report, dry_run=True)
    assert dry_run.state == "DRY_RUN"
    second_preview = preprocess_workspace(workspace)
    second_analysis = analyze_workspace(
        workspace, provider=provider, options=AnalysisOptions(batch_size=100)
    )
    elapsed = time.perf_counter() - started
    peak_rss_bytes = _peak_rss_bytes()
    sqlite_bytes = workspace.database_path.stat().st_size

    assert scan.indexed_count == 1000
    assert first_preview.processed_count == 1
    assert first_preview.cache_hit_count == 999
    assert first_preview.failed_count == 0
    assert grouped.comparison_count < 32_000
    assert first_analysis.failed_count == 0
    assert second_preview.cache_hit_count == 1000
    assert second_analysis.request_count == 0
    assert second_analysis.cache_hit_count == 1000
    assert _snapshot(source) == before
    assert not _snapshot(output)
    assert elapsed > 0
    if peak_rss_bytes is not None:
        assert peak_rss_bytes > 0
    print(
        "PHASE_H_1K_FULL_LIFECYCLE "
        f"items=1000 elapsed={elapsed:.3f}s scan_items_per_second={1000 / scan_elapsed:.1f} "
        f"preview_items_per_second={1000 / preview_elapsed:.1f} peak_rss_mib="
        f"{peak_rss_bytes / 1024 / 1024 if peak_rss_bytes is not None else 'unavailable'} "
        f"sqlite_mib={sqlite_bytes / 1024 / 1024:.2f} "
        f"cache_hits={second_preview.cache_hit_count} groups={grouped.duplicate_group_count}/"
        f"{grouped.burst_group_count} "
        f"failed={first_preview.failed_count + first_analysis.failed_count} "
        f"comparisons={grouped.comparison_count} fake_requests={first_analysis.request_count}"
    )
